
package com.slieer.ejbpro.ifc.soacookbook.ns.ws.catalog;

import java.net.MalformedURLException;
import java.net.URL;
import java.util.logging.Logger;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.1.6 in JDK 6
 * Generated source version: 2.1
 * 
 */
@WebServiceClient(name = "CatalogService", targetNamespace = "http://ns.soacookbook.com/ws/catalog", wsdlLocation = "http://localhost:8080/ejbpro_ejb/CatalogService/Catalog?wsdl")
public class CatalogService
    extends Service
{

    private final static URL CATALOGSERVICE_WSDL_LOCATION;
    private final static Logger logger = Logger.getLogger(CatalogService.class.getName());

    static {
        URL url = null;
        try {
            URL baseUrl;
            baseUrl = CatalogService.class.getResource(".");
            url = new URL(baseUrl, "http://localhost:8080/ejbpro_ejb/CatalogService/Catalog?wsdl");
        } catch (MalformedURLException e) {
            logger.warning("Failed to create URL for the wsdl Location: 'http://localhost:8080/ejbpro_ejb/CatalogService/Catalog?wsdl', retrying as a local file");
            logger.warning(e.getMessage());
        }
        CATALOGSERVICE_WSDL_LOCATION = url;
    }

    public CatalogService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public CatalogService() {
        super(CATALOGSERVICE_WSDL_LOCATION, new QName("http://ns.soacookbook.com/ws/catalog", "CatalogService"));
    }

    /**
     * 
     * @return
     *     returns Catalog
     */
    @WebEndpoint(name = "CatalogPort")
    public Catalog getCatalogPort() {
        return super.getPort(new QName("http://ns.soacookbook.com/ws/catalog", "CatalogPort"), Catalog.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns Catalog
     */
    @WebEndpoint(name = "CatalogPort")
    public Catalog getCatalogPort(WebServiceFeature... features) {
        return super.getPort(new QName("http://ns.soacookbook.com/ws/catalog", "CatalogPort"), Catalog.class, features);
    }

}

