
/**
 * Please modify this class to meet your needs
 * This class is not complete
 */

package com.slieer.webservice;

import java.util.logging.Logger;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;

/**
 * This class was generated by Apache CXF 2.5.0
 * 2011-12-08T16:24:30.011+08:00
 * Generated source version: 2.5.0
 * 
 */

@javax.jws.WebService(
                      serviceName = "HelloWebServiceService",
                      portName = "HelloWebServicePort",
                      targetNamespace = "http://webservice.ejb.ejbpro.slieer.com/",
                      wsdlLocation = "http://127.0.0.1:8080/ejbpro_ejb/HelloWebService?wsdl",
                      endpointInterface = "com.slieer.webservice.HelloWebService")
                      
public class HelloWebServiceImpl implements HelloWebService {

    private static final Logger LOG = Logger.getLogger(HelloWebServiceImpl.class.getName());

    /* (non-Javadoc)
     * @see com.slieer.webservice.HelloWebService#sayHello(java.lang.String  arg0 )*
     */
    public java.lang.String sayHello(java.lang.String arg0) { 
        LOG.info("Executing operation sayHello");
        System.out.println(arg0);
        try {
            java.lang.String _return = "_return1372801318";
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

}
