package com.slieer.webservice;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;
import javax.xml.ws.Service;

/**
 * This class was generated by Apache CXF 2.5.0
 * 2011-12-08T16:24:30.031+08:00
 * Generated source version: 2.5.0
 * 
 */
@WebServiceClient(name = "HelloWebServiceService", 
                  wsdlLocation = "http://127.0.0.1:8080/ejbpro_ejb/HelloWebService?wsdl",
                  targetNamespace = "http://webservice.ejb.ejbpro.slieer.com/") 
public class HelloWebServiceService extends Service {

    public final static URL WSDL_LOCATION;

    public final static QName SERVICE = new QName("http://webservice.ejb.ejbpro.slieer.com/", "HelloWebServiceService");
    public final static QName HelloWebServicePort = new QName("http://webservice.ejb.ejbpro.slieer.com/", "HelloWebServicePort");
    static {
        URL url = null;
        try {
            url = new URL("http://127.0.0.1:8080/ejbpro_ejb/HelloWebService?wsdl");
        } catch (MalformedURLException e) {
            java.util.logging.Logger.getLogger(HelloWebServiceService.class.getName())
                .log(java.util.logging.Level.INFO, 
                     "Can not initialize the default wsdl from {0}", "http://127.0.0.1:8080/ejbpro_ejb/HelloWebService?wsdl");
        }
        WSDL_LOCATION = url;
    }

    public HelloWebServiceService(URL wsdlLocation) {
        super(wsdlLocation, SERVICE);
    }

    public HelloWebServiceService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public HelloWebServiceService() {
        super(WSDL_LOCATION, SERVICE);
    }
    

    /**
     *
     * @return
     *     returns HelloWebService
     */
    @WebEndpoint(name = "HelloWebServicePort")
    public HelloWebService getHelloWebServicePort() {
        return super.getPort(HelloWebServicePort, HelloWebService.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns HelloWebService
     */
    @WebEndpoint(name = "HelloWebServicePort")
    public HelloWebService getHelloWebServicePort(WebServiceFeature... features) {
        return super.getPort(HelloWebServicePort, HelloWebService.class, features);
    }

}
