
package com.slieer.ejbpro.ejb.webservice;

import java.net.MalformedURLException;
import java.net.URL;
import java.util.logging.Logger;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.1.6 in JDK 6
 * Generated source version: 2.1
 * 
 */
@WebServiceClient(name = "CarWebServiceService", targetNamespace = "http://webservice.ejb.ejbpro.slieer.com/", wsdlLocation = "http://localhost:8080/ejbpro_ejb/CarWebService?wsdl")
public class CarWebServiceService
    extends Service
{

    private final static URL CARWEBSERVICESERVICE_WSDL_LOCATION;
    private final static Logger logger = Logger.getLogger(com.slieer.ejbpro.ejb.webservice.CarWebServiceService.class.getName());

    static {
        URL url = null;
        try {
            URL baseUrl;
            baseUrl = com.slieer.ejbpro.ejb.webservice.CarWebServiceService.class.getResource(".");
            url = new URL(baseUrl, "http://localhost:8080/ejbpro_ejb/CarWebService?wsdl");
        } catch (MalformedURLException e) {
            logger.warning("Failed to create URL for the wsdl Location: 'http://localhost:8080/ejbpro_ejb/CarWebService?wsdl', retrying as a local file");
            logger.warning(e.getMessage());
        }
        CARWEBSERVICESERVICE_WSDL_LOCATION = url;
    }

    public CarWebServiceService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public CarWebServiceService() {
        super(CARWEBSERVICESERVICE_WSDL_LOCATION, new QName("http://webservice.ejb.ejbpro.slieer.com/", "CarWebServiceService"));
    }

    /**
     * 
     * @return
     *     returns CarWebService
     */
    @WebEndpoint(name = "CarWebServicePort")
    public CarWebService getCarWebServicePort() {
        return super.getPort(new QName("http://webservice.ejb.ejbpro.slieer.com/", "CarWebServicePort"), CarWebService.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns CarWebService
     */
    @WebEndpoint(name = "CarWebServicePort")
    public CarWebService getCarWebServicePort(WebServiceFeature... features) {
        return super.getPort(new QName("http://webservice.ejb.ejbpro.slieer.com/", "CarWebServicePort"), CarWebService.class, features);
    }

}
