
package com.slieer.ejbpro.ejb.webservice;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.1.6 in JDK 6
 * Generated source version: 2.1
 * 
 */
@WebService(name = "CarWebService", targetNamespace = "http://webservice.ejb.ejbpro.slieer.com/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface CarWebService {


    /**
     * 
     * @param arg0
     * @return
     *     returns com.slieer.ejbpro.ejb.webservice.Car
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "callCar", targetNamespace = "http://webservice.ejb.ejbpro.slieer.com/", className = "com.slieer.ejbpro.ejb.webservice.CallCar")
    @ResponseWrapper(localName = "callCarResponse", targetNamespace = "http://webservice.ejb.ejbpro.slieer.com/", className = "com.slieer.ejbpro.ejb.webservice.CallCarResponse")
    public Car callCar(
        @WebParam(name = "arg0", targetNamespace = "")
        String arg0);

}
