CREATE TABLE `t_user_contacts` (
  `contact_id` int(10) unsigned NOT NULL AUTO_INCREMENT,
  `contact_fn` varchar(128) DEFAULT NULL,
  `contact_n` text,
  `contact_nickname` varchar(64) DEFAULT NULL,
  `contact_birthday` varchar(10) DEFAULT NULL,
  `contact_adr` text,
  `contact_label` text,
  `contact_tel` text,
  `contact_email` text,
  `contact_title` varchar(128) DEFAULT NULL,
  `contact_org` varchar(255) DEFAULT NULL,
  `contact_note` text,
  `last_modify` datetime DEFAULT NULL,
  `contact_url` text,
  `contact_xtends` text,
  `contact_mobile` text,
  `contact_index` char(1) DEFAULT NULL,
  `contact_status` tinyint(4) DEFAULT '1',
  `origin` int(4) DEFAULT '1',
  `sync_phone` tinyint(4) DEFAULT '1',
  `User_ID` int(10) unsigned NOT NULL,
  `photo_id` int(10) unsigned DEFAULT NULL,
  PRIMARY KEY (`contact_id`),
  KEY `User_ID` (`User_ID`),
  KEY `photo_id` (`photo_id`),
  KEY `FK69EAB1BC3EADE941` (`User_ID`),
  KEY `FK69EAB1BC2D9D9BAB` (`photo_id`)
) ENGINE=MyISAM AUTO_INCREMENT=74005 DEFAULT CHARSET=utf8;
