
package com.slieer.ejbpro.ifc.soacookbook.ns.ws.catalog;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.1.6 in JDK 6
 * Generated source version: 2.1
 * 
 */
@WebService(name = "Catalog", targetNamespace = "http://ns.soacookbook.com/ws/catalog")
@XmlSeeAlso({
		com.slieer.ejbpro.ifc.soacookbook.ns.ws.catalog.ObjectFactory.class,
		com.slieer.ejbpro.ifc.soacookbook.ns.catalog.ObjectFactory.class
})
public interface Catalog {


    /**
     * 
     * @param isbn
     * @return
     *     returns com.soacookbook.ns.ws.catalog.Book
     */
    @WebMethod
    @WebResult(name = "book", targetNamespace = "http://ns.soacookbook.com/catalog", partName = "book")
    @SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
    public Book getBook(
        @WebParam(name = "isbn", targetNamespace = "http://ns.soacookbook.com/catalog", partName = "isbn")
        String isbn);

    /**
     * 
     * @param id
     * @return
     *     returns java.lang.String
     */
    @WebMethod
    @WebResult(name = "title", targetNamespace = "")
    @RequestWrapper(localName = "getTitle", targetNamespace = "http://ns.soacookbook.com/ws/catalog", className = "com.soacookbook.ns.ws.catalog.GetTitle")
    @ResponseWrapper(localName = "getTitleResponse", targetNamespace = "http://ns.soacookbook.com/ws/catalog", className = "com.soacookbook.ns.ws.catalog.GetTitleResponse")
    public String getTitle(
        @WebParam(name = "id", targetNamespace = "")
        String id);

}
