
package com.soacookbook.ns.ws.catalog;

/**
 * Please modify this class to meet your needs
 * This class is not complete
 */

import java.io.File;
import java.net.MalformedURLException;
import java.net.URL;

import javax.xml.namespace.QName;

/**
 * This class was generated by Apache CXF 2.5.0
 * 2011-12-08T15:13:46.240+08:00
 * Generated source version: 2.5.0
 * 
 */
public final class Catalog_CatalogPort_Client {

    private static final QName SERVICE_NAME = new QName("http://ns.soacookbook.com/ws/catalog", "CatalogService");

    private Catalog_CatalogPort_Client() {
    }

    public static void main(String args[]) throws java.lang.Exception {
        URL wsdlURL = CatalogService.WSDL_LOCATION;
        if (args.length > 0 && args[0] != null && !"".equals(args[0])) { 
            File wsdlFile = new File(args[0]);
            try {
                if (wsdlFile.exists()) {
                    wsdlURL = wsdlFile.toURI().toURL();
                } else {
                    wsdlURL = new URL(args[0]);
                }
            } catch (MalformedURLException e) {
                e.printStackTrace();
            }
        }
      
        CatalogService ss = new CatalogService(wsdlURL, SERVICE_NAME);
        Catalog port = ss.getCatalogPort();  
        
        {
        System.out.println("Invoking getBook...");
        java.lang.String _getBook_isbn = "12345";
        com.soacookbook.ns.ws.catalog.Book _getBook__return = port.getBook(_getBook_isbn);
        System.out.println("getBook.result=" + _getBook__return);

        }

        //System.exit(0);
    }

}
