package com.soacookbook.ns.ws.catalog;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;
import javax.xml.ws.Service;

/**
 * This class was generated by Apache CXF 2.5.0
 * 2011-12-08T15:13:46.409+08:00
 * Generated source version: 2.5.0
 * 
 */
@WebServiceClient(name = "CatalogService", 
                  wsdlLocation = "http://127.0.0.1:8080/ejbpro_ejb/CatalogEJB?wsdl",
                  targetNamespace = "http://ns.soacookbook.com/ws/catalog") 
public class CatalogService extends Service {

    public final static URL WSDL_LOCATION;

    public final static QName SERVICE = new QName("http://ns.soacookbook.com/ws/catalog", "CatalogService");
    public final static QName CatalogPort = new QName("http://ns.soacookbook.com/ws/catalog", "CatalogPort");
    static {
        URL url = null;
        try {
            url = new URL("http://127.0.0.1:8080/ejbpro_ejb/CatalogEJB?wsdl");
        } catch (MalformedURLException e) {
            java.util.logging.Logger.getLogger(CatalogService.class.getName())
                .log(java.util.logging.Level.INFO, 
                     "Can not initialize the default wsdl from {0}", "http://127.0.0.1:8080/ejbpro_ejb/CatalogEJB?wsdl");
        }
        WSDL_LOCATION = url;
    }

    public CatalogService(URL wsdlLocation) {
        super(wsdlLocation, SERVICE);
    }

    public CatalogService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public CatalogService() {
        super(WSDL_LOCATION, SERVICE);
    }
    

    /**
     *
     * @return
     *     returns Catalog
     */
    @WebEndpoint(name = "CatalogPort")
    public Catalog getCatalogPort() {
        return super.getPort(CatalogPort, Catalog.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns Catalog
     */
    @WebEndpoint(name = "CatalogPort")
    public Catalog getCatalogPort(WebServiceFeature... features) {
        return super.getPort(CatalogPort, Catalog.class, features);
    }

}
