
package net.webservicex;

import java.net.MalformedURLException;
import java.net.URL;
import java.util.logging.Logger;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;


/**
 * Get one week weather forecast for valid zip code or Place name in USA
 * 
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.1.6 in JDK 6
 * Generated source version: 2.1
 * 
 */
@WebServiceClient(name = "WeatherForecast", targetNamespace = "http://www.webservicex.net", wsdlLocation = "http://www.Webservicex.net/WeatherForecast.asmx?wsdl")
public class WeatherForecast
    extends Service
{

    private final static URL WEATHERFORECAST_WSDL_LOCATION;
    private final static Logger logger = Logger.getLogger(net.webservicex.WeatherForecast.class.getName());

    static {
        URL url = null;
        try {
            URL baseUrl;
            baseUrl = net.webservicex.WeatherForecast.class.getResource(".");
            url = new URL(baseUrl, "http://www.Webservicex.net/WeatherForecast.asmx?wsdl");
        } catch (MalformedURLException e) {
            logger.warning("Failed to create URL for the wsdl Location: 'http://www.Webservicex.net/WeatherForecast.asmx?wsdl', retrying as a local file");
            logger.warning(e.getMessage());
        }
        WEATHERFORECAST_WSDL_LOCATION = url;
    }

    public WeatherForecast(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public WeatherForecast() {
        super(WEATHERFORECAST_WSDL_LOCATION, new QName("http://www.webservicex.net", "WeatherForecast"));
    }

    /**
     * 
     * @return
     *     returns WeatherForecastSoap
     */
    @WebEndpoint(name = "WeatherForecastSoap")
    public WeatherForecastSoap getWeatherForecastSoap() {
        return super.getPort(new QName("http://www.webservicex.net", "WeatherForecastSoap"), WeatherForecastSoap.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns WeatherForecastSoap
     */
    @WebEndpoint(name = "WeatherForecastSoap")
    public WeatherForecastSoap getWeatherForecastSoap(WebServiceFeature... features) {
        return super.getPort(new QName("http://www.webservicex.net", "WeatherForecastSoap"), WeatherForecastSoap.class, features);
    }

    /**
     * 
     * @return
     *     returns WeatherForecastSoap
     */
    @WebEndpoint(name = "WeatherForecastSoap12")
    public WeatherForecastSoap getWeatherForecastSoap12() {
        return super.getPort(new QName("http://www.webservicex.net", "WeatherForecastSoap12"), WeatherForecastSoap.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns WeatherForecastSoap
     */
    @WebEndpoint(name = "WeatherForecastSoap12")
    public WeatherForecastSoap getWeatherForecastSoap12(WebServiceFeature... features) {
        return super.getPort(new QName("http://www.webservicex.net", "WeatherForecastSoap12"), WeatherForecastSoap.class, features);
    }

    /**
     * 
     * @return
     *     returns WeatherForecastHttpGet
     */
    @WebEndpoint(name = "WeatherForecastHttpGet")
    public WeatherForecastHttpGet getWeatherForecastHttpGet() {
        return super.getPort(new QName("http://www.webservicex.net", "WeatherForecastHttpGet"), WeatherForecastHttpGet.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns WeatherForecastHttpGet
     */
    @WebEndpoint(name = "WeatherForecastHttpGet")
    public WeatherForecastHttpGet getWeatherForecastHttpGet(WebServiceFeature... features) {
        return super.getPort(new QName("http://www.webservicex.net", "WeatherForecastHttpGet"), WeatherForecastHttpGet.class, features);
    }

    /**
     * 
     * @return
     *     returns WeatherForecastHttpPost
     */
    @WebEndpoint(name = "WeatherForecastHttpPost")
    public WeatherForecastHttpPost getWeatherForecastHttpPost() {
        return super.getPort(new QName("http://www.webservicex.net", "WeatherForecastHttpPost"), WeatherForecastHttpPost.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns WeatherForecastHttpPost
     */
    @WebEndpoint(name = "WeatherForecastHttpPost")
    public WeatherForecastHttpPost getWeatherForecastHttpPost(WebServiceFeature... features) {
        return super.getPort(new QName("http://www.webservicex.net", "WeatherForecastHttpPost"), WeatherForecastHttpPost.class, features);
    }

}
