package com.soacookbook.ns.ws.catalog;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;

/**
 * This class was generated by Apache CXF 2.5.0
 * 2011-12-08T15:13:46.401+08:00
 * Generated source version: 2.5.0
 * 
 */
@WebService(targetNamespace = "http://ns.soacookbook.com/ws/catalog", name = "Catalog")
@XmlSeeAlso({com.soacookbook.ns.catalog.ObjectFactory.class, ObjectFactory.class})
@SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
public interface Catalog {

    @WebResult(name = "book", targetNamespace = "http://ns.soacookbook.com/catalog", partName = "book")
    @WebMethod
    public Book getBook(
        @WebParam(partName = "isbn", name = "isbn", targetNamespace = "http://ns.soacookbook.com/catalog")
        java.lang.String isbn
    );
}
