
/**
 * Please modify this class to meet your needs
 * This class is not complete
 */

package com.soacookbook.ns.ws.catalog;

import java.util.logging.Logger;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;

/**
 * This class was generated by Apache CXF 2.5.0
 * 2011-12-08T15:13:46.372+08:00
 * Generated source version: 2.5.0
 * 
 */

@javax.jws.WebService(
                      serviceName = "CatalogService",
                      portName = "CatalogPort",
                      targetNamespace = "http://ns.soacookbook.com/ws/catalog",
                      wsdlLocation = "http://127.0.0.1:8080/ejbpro_ejb/CatalogEJB?wsdl",
                      endpointInterface = "com.soacookbook.ns.ws.catalog.Catalog")
                      
public class CatalogImpl implements Catalog {

    private static final Logger LOG = Logger.getLogger(CatalogImpl.class.getName());

    /* (non-Javadoc)
     * @see com.soacookbook.ns.ws.catalog.Catalog#getBook(java.lang.String  isbn )*
     */
    public com.soacookbook.ns.ws.catalog.Book getBook(java.lang.String isbn) { 
        LOG.info("Executing operation getBook");
        System.out.println(isbn);
        try {
            com.soacookbook.ns.ws.catalog.Book _return = new com.soacookbook.ns.ws.catalog.Book();
            com.soacookbook.ns.ws.catalog.Author _returnAuthor = new com.soacookbook.ns.ws.catalog.Author();
            _returnAuthor.setFirstName("FirstName-19628385");
            _returnAuthor.setLastName("LastName2102327125");
            _return.setAuthor(_returnAuthor);
            com.soacookbook.ns.ws.catalog.Category _returnCategory = com.soacookbook.ns.ws.catalog.Category.PROGRAMMING;
            _return.setCategory(_returnCategory);
            _return.setIsbn("Isbn-1810339935");
            _return.setPrice(0.7530184712159257);
            _return.setTitle("Title-378662013");
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

}
